Bypasses bot detection

diff --git a/happypanda b/happypanda
--- a/happypanda
+++ b/happypanda
@@ -12,7 +12,7 @@ declare -i ITERATION=0
 declare -i MAX_ITERATION=0
 BAD_PAGE='<td class="ptdd">&gt;<'
 SLEEP="0.1"
-COOKIES_FILE="${HOME%/}/.exhentai.cookies"
+COOKIES_CONTENT="${HOME%/}/.exhentai.cookies"
 METADATA=true
 
 help(){
@@ -38,9 +38,7 @@ help(){
 }
 
 incomplete_quit(){
-    pushd -0 >/dev/null 2>&1
-    dirs -c >/dev/null 2>&1
-    [[ ${CURRENT_PAGE} ]] && echo "${CURRENT_PAGE}" > "${TITLE}/.incomplete"
+    [[ ${PAGE} ]] && echo "${PAGE}" > ".incomplete"
     [[ ${1} ]] && STATUS=${1} || STATUS=5
     quit ${STATUS}
 }
@@ -53,24 +51,22 @@ quit(){
 
 get_title(){
     sleep "${SLEEP}"
-    TITLE="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${1}" -O- | grep -o -E '<h1 id="gn">[^<]*<' | sed 's/.*<h1 id="gn">\([^<]*\)</\1/')"
+    TITLE="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${1}" -O- | grep -o -E '<h1 id="gn">[^<]*<' | sed 's/.*<h1 id="gn">\([^<]*\)</\1/')"
 }
 
 get_metadata(){
     if [[ ${METADATA} ]]; then
         sleep "${SLEEP}"
-        local PAGE="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${1}" -O-)"
+        local PAGE="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${1}" -O-)"
         local PAGE_TITLE="$(echo -e \{\\n \ \"Title\":\"${2}\",)"
         local PAGE_URL="  \"URL\":\"${1}\","
         local PAGE_DATE="  \"Date\":\"$(date '+%Y-%m-%d %H:%M')\","
-        local PAGE_TYPE="$(grep -E -o '<[^<]*class="ic"[^>]*>' <<< ${PAGE} | sed 's/.*alt="\([^"]*\)".*/  "Type":"\1",/')"
-        local PAGE_INFO="$(grep -E -o '<div id="gdd".*</div><div id="gdr"' <<< ${PAGE} | sed -e 's/<div id="gdd"><table><tr>/  /' -e 's: &nbsp;<span.*</span>::' -e 's:</td></tr><tr>:",\n  :g' -e 's:</td><td[^>]*>:":g' -e 's/<[^>]*>\([^:]*\):/"\1":/g' -e 's:</td.*<div id="gdr":",:')"
-        local PAGE_RATING="$(grep -E -o '<td id="grt1">.*<td id="rating_label"[^<]*' <<< ${PAGE} | sed 's!<[^>]*>\([^:]*\):<.*id="rating_count"[^>]*>\([^<]*\).*id="rating_label"[^>]*>\([^:]*\):.\(.*\)!  "\1s":"\2",\n  "\3":"\4",!')"
-        local PAGE_TAGS="$(grep -E -o '<div id="taglist".*</div><div id="tagmenu_act"' <<< ${PAGE} | sed -e 's!:</td><td><div[^>]*>!":[!g' -e 's:<a[^>]*>\([^<]*\)</a>:"\1":g' -e 's:</div><div[^>]*>:,:g' -e 's:</div></td></tr>:],\n    :g' -e 's/<tr><td[^>]*>/"/g' -e 's/<div id="taglist"><table>/  "Tags":{\n    /' -e 's:,\n    </table></div><div id="tagmenu_act":\n  }\n}:')"
+        local PAGE_INFO="$(echo ${PAGE} | grep -E -o '<div id="gdd".*</div><div id="gdr"' | sed -e 's/<div id="gdd"><table><tr>/  /' -e 's: &nbsp;<span.*</span>::' -e 's:</td></tr><tr>:",\n  :g' -e 's:</td><td[^>]*>:":g' -e 's/<[^>]*>\([^:]*\):/"\1":/g' -e 's:</td.*<div id="gdr":",:')"
+        local PAGE_RATING="$(echo ${PAGE} | grep -E -o '<td id="grt1">.*<td id="rating_label"[^<]*' | sed 's!<[^>]*>\([^:]*\):<.*id="rating_count"[^>]*>\([^<]*\).*id="rating_label"[^>]*>\([^:]*\):.\(.*\)!"\1s":"\2",\n"\3":"\4",!')"
+        local PAGE_TAGS="$(echo ${PAGE} | grep -E -o '<div id="taglist".*</div><div id="tagmenu_act"' | sed -e 's!:</td><td><div[^>]*>!":[!g' -e 's:<a[^>]*>\([^<]*\)</a>:"\1":g' -e 's:</div><div[^>]*>:,:g' -e 's:</div></td></tr>:],\n    :g' -e 's/<tr><td[^>]*>/"/g' -e 's/<div id="taglist"><table>/  "Tags":{\n    /' -e 's:,\n    </table></div><div id="tagmenu_act":\n  }\n}:')"
         exec 3<> "${2}/metadata.json"
         echo -e "${PAGE_TITLE}"  >&3
         echo -e "${PAGE_URL}"    >&3
-        echo -e "${PAGE_TYPE}"   >&3
         echo -e "${PAGE_DATE}"   >&3
         echo -e "${PAGE_INFO}"   >&3
         echo -e "${PAGE_RATING}" >&3
@@ -81,11 +77,10 @@ get_metadata(){
 
 get_start_page(){
     sleep "${SLEEP}"
-    if [[ ${RESUME} ]]; then
-        local IMAGE_PAGE="${RESUME}"
-        RESUME=''
+    if [[ -f .incomplete ]]; then
+        read -r IMAGE_PAGE < .incomplete
     else
-        local IMAGE_PAGE="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${1}" -O- | grep -o -E '<a href="https://exhentai.org/s/[^"]*"><img' | sed 's/[^"]*"\([^"]*\)".*/\1/' | head -n 1)"
+        local IMAGE_PAGE="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${1}" -O- | grep -o -E '<a href="https://exhentai.org/s/[^"]*"><img' | sed 's/[^"]*"\([^"]*\)".*/\1/' | head -n 1)"
     fi
     download_pages "${IMAGE_PAGE}"
 }
@@ -97,12 +92,12 @@ get_search_pages(){
         local URL="https://exhentai.org/?f_search=${TAGS}&f_apply=Apply+Filter${FILTERS}"
     fi
     sleep "${SLEEP}"
-    GALLERIES="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${URL}" -O- | grep -E -o 'https://exhentai.org/g/[^"]*')"
+    GALLERIES="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${URL}" -O- | grep -E -o 'https://exhentai.org/g/[^"]*')"
     for GALLERY in $(echo ${GALLERIES}); do
         download "${GALLERY}"
     done
     sleep "${SLEEP}"
-    local NEXT_PAGE="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${URL}" -O- | grep -E -o '<[^>]*>&gt;<' | head -n 1 | sed -e 's/.*href="\([^"]*\)".*/\1/' -e 's/&amp;/\&/g')"
+    local NEXT_PAGE="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${URL}" -O- | grep -E -o '<[^>]*>&gt;<' | head -n 1 | sed -e 's/.*href="\([^"]*\)".*/\1/' -e 's/&amp;/\&/g')"
     if [[ "${BAD_PAGE}" == "${NEXT_PAGE}" ]]; then
         return 0
     else
@@ -111,14 +106,15 @@ get_search_pages(){
 }
 
 download_pages(){
-    CURRENT_PAGE="${1}"
-    local PAGE="$(wget -c -q --load-cookies="${COOKIES_FILE}" "${CURRENT_PAGE}" -O-)"
+    local CURRENT_PAGE="${1}"
+    PAGE="$(wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${CURRENT_PAGE}" -O-)"
     local NEXT_PAGE="$(echo "${PAGE}" | grep -o -E '<a id="next" onclick="[^"]*"[^>]*>' | tail -n 1 | sed 's/.*href="\([^"]*\)">/\1/')"
     local IMAGE="$(echo "${PAGE}" | grep -o -E '<img id="img"[^>]*>' | sed 's/.*src="\([^"]*\)".*/\1/')"
     sleep "${SLEEP}"
     download_image "${IMAGE}"
     if [[ "${CURRENT_PAGE##*-}" -eq "${NEXT_PAGE##*-}" ]]; then
         rm ".incomplete" 2>/dev/null
+        unset PAGE
         return 0
     else
         download_pages "${NEXT_PAGE}"
@@ -140,19 +136,15 @@ download_image(){
     sleep "${SLEEP}"
     [[ ${SKIP} ]] && [[ -f "${IMAGE}" ]] && return 1
     echo "Downloading ${IMAGE}"
-    wget -c -q --load-cookies="${COOKIES_FILE}" "${1}" -O "${IMAGE}"
+    wget -c -q --header="Cookie: ${COOKIES_CONTENT}" "${1}" -O "${IMAGE}"
 }
 
 download(){
     local URL="${1}"
     get_title "${URL}"
     echo "Creating directory: ${TITLE}"
-    if [[ -f "${TITLE}/.incomplete" ]];then
-        echo "Resuming download"
-        read -r RESUME < "${TITLE}/.incomplete"
-        get_metadata "${URL}" "${TITLE}"
-        rm "${TITLE}/.incomplete"
-    elif [[ ${SKIP_DIRS} ]]; then
+
+    if [[ ${SKIP_DIRS} ]]; then
         mkdir "${TITLE}" 2>/dev/null
         DIR_EXISTS=${?}
         get_metadata "${URL}" "${TITLE}"
@@ -179,7 +171,22 @@ download(){
     [[ ${ITERATION} -eq ${MAX_ITERATION} ]] && quit
 }
 
-trap incomplete_quit SIGINT SIGTERM SIGQUIT
+use_cookies(){
+    if [[ ! -f "${HOME%/}/.exhentai.cookies" ]]; then
+        echo "Cookies File not found."
+        echo "Specify the location of your browser cookies with \"--cookies\" to generate"
+        exit 1
+    else
+        COOKIES_CONTENT="$(cat "${HOME%/}/.exhentai.cookies")"
+    fi
+}
+
+get_cookies(){
+    COOKIES_CONTENT="$(sqlite3 -separator '=' ${1} 'SELECT name, value FROM moz_cookies WHERE host == ".e-hentai.org";' | tr '\n' ';' | sed 's/.$//')"
+    echo "${COOKIES_CONTENT}" > "${HOME%/}/.exhentai.cookies"
+}
+
+trap incomplete_quit SIGINT SIGTERM SIGQUIT EXIT
 
 while [ "${#}" -ne 0 ]; do
     case ${1} in
@@ -286,10 +293,10 @@ while [ "${#}" -ne 0 ]; do
     esac
 done
 
-if [[ ! -f "${COOKIES_FILE}" ]]; then
-    echo "Cookies File not found."
-    echo "Put wget format cookies file in ${HOME%/}/.exhentai.cookies"
-    echo "Or specify it with --cookies"
+if [[ "${COOKIES_FILE}" ]]; then
+    get_cookies "${COOKIES_FILE}"
+else
+    use_cookies
 fi
 if [[ "${URL}" ]]; then
     download "${URL}"
